#!/bin/bash

sudo mkdir -p /root/.config
sudo mkdir -p /home/andrax/.config

sudo cp -Rf /opt/ANDRAX/.config/ /root/.config/
sudo cp -Rf /opt/ANDRAX/.config/ /home/andrax/.config/

sudo chmod -R 777 /root/.config /home/andrax/.config/

cd /opt/ANDRAX/CrackMapExec

sudo poetry run cmedb "$@"
